import Link from "next/link";
import "./globals.css";
import type {Metadata} from "next";
import style from "./layout.module.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
        <body>
        <nav>
            <div className={style.navContainer}>
                <h1>CRUD Spring Boot NextJS </h1>
                <ul>
                    <li>
                        <Link href="/">Product list</Link>
                    </li>
                    <li>
                        <Link href="/create">Register Product</Link>
                    </li>
                    <li>
                        <Link href="/update">Update Product</Link>
                    </li>
                    <li>
                        <Link href="/delete">Delete Product</Link>
                    </li>
                </ul>
            </div>
        </nav>
        <hr/>
        {children}
        </body>
        </html>
    );
}
